%YAML:1.0
---
model_type: KANNALA_BRANDT
camera_name: camera
image_width: 512
image_height: 512

projection_parameters:
   k2: 0.00
   k3: 0.00
   k4: 0.00
   k5: 0.00
   mu: 190.0
   mv: 190.0
   u0: 256.0
   v0: 256.0
